/**
 * Regenerates the npm section of public/third-party-notices.txt.
 *
 * The file's link in the app promises "full license texts for bundled code";
 * before this script it carried only the hand-written DTLN worklet notices,
 * while the JS bundle ships hundreds of MIT/Apache/BSD packages whose
 * licenses require their notices to travel with distributed copies.
 *
 * Everything above the marker line is hand-maintained (the DTLN wasm story);
 * everything below is generated here from `pnpm licenses` and the packages'
 * own LICENSE files, deduplicated by identical text so the stock MIT text
 * appears once with every package that uses it listed above it.
 */
import { execSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "public", "third-party-notices.txt");
const MARKER =
  "================ GENERATED NPM LICENSE NOTICES BELOW - do not edit ================";

const raw = execSync("pnpm licenses list --prod --json", {
  cwd: root,
  maxBuffer: 64 * 1024 * 1024,
}).toString();
const byLicense = JSON.parse(raw);

function licenseText(pkgPath) {
  let entries;
  try {
    entries = readdirSync(pkgPath);
  } catch {
    return null;
  }
  const match = entries.find((f) =>
    /^(licen[cs]e|copying|notice)(\.|$)/i.test(f)
  );
  if (!match) return null;
  try {
    return readFileSync(join(pkgPath, match), "utf8").trim();
  } catch {
    return null;
  }
}

// text -> { packages: [{name, license}] }
const byText = new Map();
const missing = [];
for (const [license, pkgs] of Object.entries(byLicense)) {
  for (const p of pkgs) {
    const text = licenseText(p.paths?.[0] ?? "");
    const entry = `${p.name} (${license})`;
    if (!text) {
      missing.push(entry + (p.homepage ? ` - ${p.homepage}` : ""));
      continue;
    }
    const bucket = byText.get(text) ?? [];
    bucket.push(entry);
    byText.set(text, bucket);
  }
}

const sections = [...byText.entries()]
  .sort((a, b) => b[1].length - a[1].length)
  .map(([text, pkgs]) => {
    const head = pkgs.sort().join("\n");
    return `${"-".repeat(80)}\n${head}\n${"-".repeat(80)}\n\n${text}\n`;
  });

const generated = [
  MARKER,
  "",
  `The JavaScript bundle includes the following npm packages. Identical`,
  `license texts are printed once, with every package that ships under that`,
  `exact text listed above it. Regenerated by scripts/generate-notices.mjs`,
  `from the packages' own LICENSE files at build time.`,
  "",
  ...sections,
  ...(missing.length
    ? [
        "-".repeat(80),
        "Packages whose tarball carries no license file (license identifier",
        "from their package.json; text available at the linked homepage):",
        "-".repeat(80),
        "",
        ...missing.sort(),
        "",
      ]
    : []),
].join("\n");

const current = readFileSync(OUT, "utf8");
const markerAt = current.indexOf(MARKER);
const head = (markerAt >= 0 ? current.slice(0, markerAt) : current).trimEnd();
writeFileSync(OUT, head + "\n\n" + generated + "\n");
console.log(
  `[notices] ${byText.size} unique license texts, ` +
    `${[...byText.values()].reduce((n, v) => n + v.length, 0)} packages, ` +
    `${missing.length} without a license file`
);
